version: "3"

services:
  mysql:
    container_name: diet_query
    image: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=diet123
      - MYSQL_DATABASE=diet
      - MYSQL_USER=diet
      - MYSQL_PASSWORD=diet123
    ports:
      - 3306:3306